---
title: "GSK_Assessment"
author: "Kamran KHAN"
date: "21/03/2022"
output:
  pdf_document
  
---


```{r  setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# covert to data format from ISO
# install.packages("ISOweek")
library(ISOweek)
library(remotes)
library(plotly)
# install_github('vincentarelbundock/countrycode')
library(countrycode)
library(finalfit)
library(tinytex)
```


```{r}

# load the data in csv
gsk_data <- read.csv("gsk_covid_data.csv")
head(gsk_data)

# convert the ISOWeekYear column to dates
gsk_data$Date <-  ISOweek::ISOweek2date(paste0(gsk_data$YearWeekISO, "-1"))

# factoring the target age groups 
# and combining them into fewer groups 

gsk_data <- gsk_data%>%
  mutate(Groups = ifelse(TargetGroup =="Age<18" | TargetGroup== "Age0_4"| TargetGroup=="Age5_9" |TargetGroup=="Age10_14"| TargetGroup== "Age15_17", "Under 18",
            ifelse(TargetGroup=="Age18_24" | TargetGroup == "Age25_49" | TargetGroup=="Age50_59" |  TargetGroup=="ALL" |TargetGroup=="1_Age<60","18-59",                        ifelse(TargetGroup=="Age60_69" | TargetGroup=="Age70_79" | TargetGroup=="Age80+" | TargetGroup=="1_Age60+", "60+",
               ifelse(TargetGroup=="LTCF","LTC residencts",
                ifelse(TargetGroup=="HCW","Healthcare workers","Not known"))))))

# Convert countries ISO codes to country names 
gsk_data$Country <- countrycode(gsk_data$ReportingCountry, origin = "iso2c", destination = "country.name")

# The above line didn't convert the country code "EL" , so I have to google what country was it.-- The EL code is for Greece

gsk_data$Country <- with(gsk_data, ifelse(ReportingCountry == "EL", "Greece", Country))


# Create new variable: number of days
country_gsk <- gsk_data %>% group_by(Country) %>% mutate(cum_FirstDoses=cumsum(as.numeric(FirstDose)),cum_SecondDoses=cumsum(SecondDose), days = Date - first(Date) + 1)


# Aggregate at world level
world <- country_gsk %>% group_by(Date) %>% summarize(People_vaccinated=sum(cum_FirstDoses), Fully_vaccinated=sum(cum_SecondDoses))
# 
# SUMMARY STATISTICS
summary(country_gsk)
by(country_gsk$FirstDose,country_gsk$Country, summary)
by(country_gsk$SecondDose,country_gsk$Country, summary)

by( country_gsk$cum_FirstDoses,country_gsk$Country, summary)
by( country_gsk$cum_SecondDoses,country_gsk$Country, summary)

# second doses by age groups
by( country_gsk$SecondDose,country_gsk$Groups, summary)



```


```{r}

# select records for Italy

gsk_ItalyData <- country_gsk%>%
 filter(Country == "Italy")%>%
  select(YearWeekISO,Date, Population, FirstDose, SecondDose,Vaccine ,Groups)



# vaccination progress


vaccine_gsk <- gsk_ItalyData %>%
  group_by(Date)%>%
  mutate(`First dose` = round(sum(FirstDose)/ Population * 100, 3),
         `Fully vaccinated` = round(sum(SecondDose)/ Population  * 100, 3)) %>%
  select(Date, `First dose`, `Fully vaccinated`)%>%
  gather("doses", "Population share", -c(Date)) %>%
  mutate(doses = factor(doses))

vac_gsk <- ggplot(data = vaccine_gsk, aes(x = Date, y = `Population share`, fill = doses)) +
  geom_area(position = "identity") +
  theme_classic() +
  scale_fill_brewer(palette = "Green") +
  scale_x_date(date_breaks = "4 month") +
  labs(title = "Covid-19 vaccination progress in Italy ",
       x = "Date", y = "Share of Population(%)",
       fill = NULL, caption = "Data: GSK") +
  theme(plot.title = element_text(hjust = -0.25), legend.position = "bottom")

ggplotly(vac_gsk) %>%
   layout(hovermode = "x", legend = list(orientation = "h", xanchor = "center", x = 0.5, y = -0.1))
  
```



# The above results for vaccination progress for Italy using the data provided, doesnt seems right. I wanted to check the vaccination progress for Italy using the COVID 19 data available online and I got the results below which seems to be correct.








```{r }

Italy <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv") %>%
  filter(location == "Italy")%>%
  select(date, population, people_vaccinated, people_fully_vaccinated)

```


### Vaccination progress
```{r}
# Find out the rows where the second dose data are NAs when first dose were given at the start of the vaccination process
rows <- which(is.na(Italy$people_fully_vaccinated) & !is.na(Italy$people_vaccinated))
Italy[rows, "people_fully_vaccinated"] = 0  # Change the NA values to 0

vaccine <- Italy %>%
  mutate(`First dose` = round(people_vaccinated / population * 100, 3),
         `Fully vaccinated` = round(people_fully_vaccinated / population  * 100, 3)) %>%
  select(date, `First dose`, `Fully vaccinated`)%>%
  drop_na(`First dose`) %>%
  gather("doses", "Population share", -c(date)) %>%
  mutate(doses = factor(doses))

vac <- ggplot(data = vaccine, aes(x = date, y = `Population share`, fill = doses)) +
  geom_area(position = "identity") +
  theme_classic() +
  scale_fill_brewer(palette = "Green") +
  scale_x_date(date_breaks = "2 month") +
  labs(title = "Covid-19 vaccination progress in Italy ",
       x = "Date", y = "Share of Population(%)",
       fill = NULL, caption = "Data: OWID") +
  theme(plot.title = element_text(hjust = -0.25), legend.position = "bottom")

ggplotly(vac) %>%
   layout(hovermode = "x", legend = list(orientation = "h", xanchor = "center", x = 0.5, y = -0.1))
```
```{r}

# logistic regression model to check the association between age groups and getting vaccinated 
kk <- gsk_data

kk <- kk %>% 
  mutate(vaccinated = ifelse(FirstDose >0 ,1,0))%>%
  mutate(fullyvaxed= ifelse(SecondDose>0,1,0))

kk$vaccinated <- factor(kk$vaccinated)

fit1 <- glm(vaccinated ~ Groups, data = kk, family = binomial)
summary(fit1)

# exponentiate the coefficients 
coef(fit1)%>%exp()

# 95% CI
confint(fit1)%>%exp()

library(broom)

fit1 %>% 
  tidy(conf.int= TRUE, exp = TRUE)

# I dont think this is any useful model because of I didnt not see any other variable in the data which I could think of  using in a model
# However in this model the aim was to explore if there was any association between between age group and getting vaccinated at first time (first dose)
# here the reference group is the 18-59 age group and the outcome variable is getting vaccinated (first dose (Y/N))
```